version: '3'

services:

  service:
    build:
      context: dev/example-service
      dockerfile: Dockerfile
    tty: true
    depends_on:
      - db-migrator
      - storage

  db-migrator:
    image: akaeigenspace/db-migrator
    ports:
      - 4010:4010
    environment:
      DB_HOST: storage
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      CHANGELOG_FILENAME: master.xml

  storage:
    image: postgres:11.11-alpine
    container_name: storage
    hostname: storage
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  postgres-data: