###

// Positive case: Send an archive with a changelog
POST http://localhost:4010/migrate/{{service}}/{{database}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="changelog"; filename="changelog.tar"

< ./data/changelog.tar

###

// Negative case: Try to send several files
POST http://localhost:4010/migrate/{{service}}/{{database}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="changelog"; filename="changelog.tar"

< ./data/changelog.tar

--boundary
Content-Disposition: form-data; name="master"; filename="master.xml"

// 'master.xml' file with the 'Text' content will be created and uploaded
Text